pipeline {
  agent any
  tools { 
        maven 'Maven_3_2_5'  
    }
  environment {
        SNYK_TOKEN = credentials('SNYK_TOKEN')
    }
  stages {
    stage('CompileandRunSonarAnalysis') {
            steps {	
                dir('jenkins-k8s-sast-sca-sonarcloud-creation') {
                    sh '''
                        mvn clean verify sonar:sonar -rf \
                        -Dsonar.projectKey=javabuggywebapp \
                        -Dsonar.organization=javabuggywebapp \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.token=1c67a7b0ed4df3e854ccbe03fecf71f381276d13
                    '''
                }
            }
    }
      
    stage('RunSCAAnalysisUsingSnyk') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('jenkins-k8s-sast-sca-sonarcloud-creation') {
                        sh '''
                            mvn snyk:test -fn
                            mvn snyk:monitor
                        '''
                    }
                }
            }
    }

    stage('Build') { 
            steps { 
               withDockerRegistry([credentialsId: "dockerlogin", url: ""]) {
                 script{
                    app =  docker.build("asg")
                 }
               }
            }
    }

    stage('Push') {
            steps {
                script{
                    docker.withRegistry('https://209479307795.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:aws-credentials') {
                        app.push("latest")
                    }
                }
            }
    }
  }
}
