pipeline {
  agent any
  tools { 
        maven 'Maven_3_5_2'  
    }
   stages{
    stage('CompileandRunSonarAnalysis') {
            steps {	
		sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=javabuggywebapp -Dsonar.organization=javabuggywebapp -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=1c67a7b0ed4df3e854ccbe03fecf71f381276d13'
			}
        } 
  }
}
